services:
  - type: worker
    name: nekto-voice-web
    env: python
    region: frankfurt
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "honcho start -f Procfile.dev"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nekto-db
          property: connectionString
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_CHAT_ID
        sync: false
      - key: TEAM_INVITE_CODE
        value: nekto2026

databases:
  - name: nekto-db
    region: frankfurt
    plan: free
