# Generated by Django 5.2.17 on 2026-09-09 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название тайтла')),
                ('category', models.CharField(choices=[('anime', 'Аниме'), ('dorama', 'Дорама'), ('movie', 'Фильм'), ('series', 'Сериал')], max_length=20, verbose_name='Категория')),
                ('genres', models.CharField(max_length=255, verbose_name='Жанры (через запятую)')),
                ('is_hentai', models.BooleanField(default=False, verbose_name='Жанр Хентай (18+)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='Постер')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер серии')),
                ('subtitle_names', models.FileField(blank=True, null=True, upload_to='subs/names/', verbose_name='Субтитры: Имена Актёров (.ass)')),
                ('subtitle_signs', models.FileField(blank=True, null=True, upload_to='subs/signs/', verbose_name='Субтитры: Надписи (.ass)')),
                ('subtitle_general', models.FileField(blank=True, null=True, upload_to='subs/general/', verbose_name='Субтитры: Общие (.ass)')),
                ('is_ready_for_mixing', models.BooleanField(default=False, verbose_name='Готово к сведению')),
                ('final_audio', models.FileField(blank=True, null=True, upload_to='final_audio/', verbose_name='Сведенная аудиодорожка')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='core.title')),
            ],
        ),
        migrations.CreateModel(
            name='TrackAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=100, verbose_name='Имя персонажа / Роль')),
                ('voice_file', models.FileField(blank=True, null=True, upload_to='voice_tracks/', verbose_name='Аудиодорожка (.wav / .flac)')),
                ('is_submitted', models.BooleanField(default=False, verbose_name='Сдано')),
                ('dubber', models.ForeignKey(limit_choices_to={'profile__role': 'dubber'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.episode')),
            ],
        ),
        migrations.CreateModel(
            name='FixNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timecode', models.CharField(help_text='Например, 04:12', max_length=20, verbose_name='Таймкод')),
                ('comment', models.TextField(verbose_name='Замечание')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Исправлено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixes', to='core.trackassignment')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'Зритель'), ('dubber', 'Даббер'), ('sound_engineer', 'Звукорежиссер'), ('translator', 'Переводчик'), ('subber', 'Саббер'), ('curator', 'Куратор'), ('admin', 'Администратор')], default='viewer', max_length=20, verbose_name='Роль в команде')),
                ('telegram_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram ID')),
                ('reaper_skills', models.BooleanField(default=False, verbose_name='Владеет Reaper')),
                ('equipment_info', models.TextField(blank=True, null=True, verbose_name='Оборудование / Микрофон')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
