# Generated by Django 5.2.17 on 2026-09-09 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'verbose_name': 'Эпизод', 'verbose_name_plural': 'Эпизоды'},
        ),
        migrations.AlterModelOptions(
            name='fixnotice',
            options={'verbose_name': 'Уведомление об исправлении', 'verbose_name_plural': 'Уведомления об исправлениях'},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': 'Тайтл', 'verbose_name_plural': 'Тайтлы'},
        ),
        migrations.AlterModelOptions(
            name='trackassignment',
            options={'verbose_name': 'Распределение роли', 'verbose_name_plural': 'Распределение ролей'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль участника', 'verbose_name_plural': 'Профили участников'},
        ),
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='core.title', verbose_name='Тайтл'),
        ),
        migrations.AlterField(
            model_name='fixnotice',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixes', to='core.trackassignment', verbose_name='Назначенная роль'),
        ),
        migrations.AlterField(
            model_name='fixnotice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='trackassignment',
            name='dubber',
            field=models.ForeignKey(limit_choices_to={'profile__role': 'dubber'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Даббер'),
        ),
        migrations.AlterField(
            model_name='trackassignment',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.episode', verbose_name='Эпизод'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
