# Generated by Django 5.2.17 on 2026-09-09 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_episode_options_alter_fixnotice_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={},
        ),
        migrations.AlterModelOptions(
            name='trackassignment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.RemoveField(
            model_name='episode',
            name='final_audio',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='is_ready_for_mixing',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='subtitle_general',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='subtitle_names',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='subtitle_signs',
        ),
        migrations.RemoveField(
            model_name='title',
            name='category',
        ),
        migrations.RemoveField(
            model_name='title',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='title',
            name='is_hentai',
        ),
        migrations.RemoveField(
            model_name='title',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='trackassignment',
            name='is_submitted',
        ),
        migrations.RemoveField(
            model_name='trackassignment',
            name='voice_file',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='equipment_info',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='reaper_skills',
        ),
        migrations.AddField(
            model_name='episode',
            name='is_ready',
            field=models.BooleanField(default=False, verbose_name='Серия полностью собрана'),
        ),
        migrations.AddField(
            model_name='episode',
            name='is_translated',
            field=models.BooleanField(default=False, verbose_name='Перевод готов'),
        ),
        migrations.AddField(
            model_name='title',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Группы в Telegram'),
        ),
        migrations.AddField(
            model_name='trackassignment',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='tracks/', verbose_name='Аудиофайл'),
        ),
        migrations.AddField(
            model_name='trackassignment',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Замечания / Фиксы'),
        ),
        migrations.AddField(
            model_name='trackassignment',
            name='status',
            field=models.CharField(choices=[('pending', '⏳ Не сдано'), ('submitted', '📥 На проверке'), ('fix_required', '🛠 Нужен фикс'), ('approved', '✅ Принято')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_bind_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='core.title'),
        ),
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trackassignment',
            name='character_name',
            field=models.CharField(max_length=255, verbose_name='Персонаж'),
        ),
        migrations.AlterField(
            model_name='trackassignment',
            name='dubber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trackassignment',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.episode'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('director', 'Режиссёр'), ('dubber', 'Даббер'), ('sound', 'Звукорежиссёр'), ('translator', 'Переводчик')], default='dubber', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='FixNotice',
        ),
    ]
