# Generated by Django 5.2.17 on 2026-09-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_episode_options_alter_title_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн сдачи'),
        ),
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
    ]
