# Generated by Django 5.2.17 on 2026-09-09 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_episode_deadline_alter_title_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'verbose_name': 'Серию', 'verbose_name_plural': 'Серии'},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': 'Тайтл', 'verbose_name_plural': 'Тайтлы (Проекты)'},
        ),
        migrations.AlterModelOptions(
            name='trackassignment',
            options={'verbose_name': 'Задачу на озвучку', 'verbose_name_plural': 'Задачи на озвучку'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AddField(
            model_name='episode',
            name='subtitles_file',
            field=models.FileField(blank=True, null=True, upload_to='subtitles/', verbose_name='Файл субтитров (.ass / .srt)'),
        ),
        migrations.AddField(
            model_name='episode',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Видеофайл серии'),
        ),
        migrations.AddField(
            model_name='trackassignment',
            name='subtitles_character_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Имя/Тег в субтитрах'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='core.title', verbose_name='Тайтл'),
        ),
        migrations.AlterField(
            model_name='trackassignment',
            name='character_name',
            field=models.CharField(max_length=255, verbose_name='Имя персонажа'),
        ),
        migrations.AlterField(
            model_name='trackassignment',
            name='dubber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Даббер'),
        ),
        migrations.AlterField(
            model_name='trackassignment',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.episode', verbose_name='Серия'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('director', 'Режиссёр'), ('dubber', 'Даббер'), ('sound', 'Звукорежиссёр'), ('translator', 'Переводчик')], default='dubber', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_bind_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Код привязки'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
