# Generated by Django 5.2.17 on 2026-09-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_episode_options_alter_title_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackassignment',
            name='subtitles_character_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Имя в субтитрах'),
        ),
    ]
