# Generated by Django 5.2.17 on 2026-09-09 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_trackassignment_subtitles_character_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackassignment',
            name='subtitles_character_name',
        ),
        migrations.AlterField(
            model_name='trackassignment',
            name='character_name',
            field=models.CharField(max_length=255, verbose_name='Персонаж / Тег в субтитрах'),
        ),
    ]
