# Generated by Django 5.2.17 on 2026-09-09 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_title_team_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={},
        ),
        migrations.AlterModelOptions(
            name='trackassignment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.RemoveField(
            model_name='episode',
            name='subtitles_file',
        ),
        migrations.RemoveField(
            model_name='trackassignment',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='trackassignment',
            name='comment',
        ),
        migrations.AddField(
            model_name='title',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='бложка / остер'),
        ),
        migrations.AddField(
            model_name='trackassignment',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Сдано'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(default='ктивен', max_length=50, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_username',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='episode',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='едлайн'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='is_ready',
            field=models.BooleanField(default=False, verbose_name='отово'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='is_translated',
            field=models.BooleanField(default=False, verbose_name='ереведено'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='number',
            field=models.IntegerField(verbose_name='омер серии'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='core.title'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='айл серии (MP4)'),
        ),
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='писание'),
        ),
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(max_length=255, verbose_name='азвание'),
        ),
        migrations.AlterField(
            model_name='title',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='titles', to=settings.AUTH_USER_MODEL, verbose_name='оманда'),
        ),
        migrations.AlterField(
            model_name='title',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Telegram Chat ID'),
        ),
        migrations.AlterField(
            model_name='trackassignment',
            name='character_name',
            field=models.CharField(default='', max_length=100, verbose_name='ерсонаж / оль'),
        ),
        migrations.AlterField(
            model_name='trackassignment',
            name='dubber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='аббер'),
        ),
        migrations.AlterField(
            model_name='trackassignment',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.episode'),
        ),
        migrations.AlterField(
            model_name='trackassignment',
            name='status',
            field=models.CharField(default=' работе', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(default='частник', max_length=50, verbose_name='оль'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_bind_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='од привязки'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
