# Generated by Django 5.2.17 on 2026-09-09 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_episode_options_alter_title_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='is_ready',
            field=models.BooleanField(default=False, verbose_name='Готово'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='is_translated',
            field=models.BooleanField(default=False, verbose_name='Переведено'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='number',
            field=models.IntegerField(verbose_name='Номер серии'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Файл серии (MP4)'),
        ),
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='title',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='Обложка / Постер'),
        ),
        migrations.AlterField(
            model_name='title',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='titles', to=settings.AUTH_USER_MODEL, verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='trackassignment',
            name='character_name',
            field=models.CharField(default='', max_length=100, verbose_name='Персонаж / Роль'),
        ),
        migrations.AlterField(
            model_name='trackassignment',
            name='dubber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Даббер'),
        ),
        migrations.AlterField(
            model_name='trackassignment',
            name='status',
            field=models.CharField(default='В работе', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(default='Участник', max_length=50, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(default='Активен', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_bind_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Код привязки'),
        ),
    ]
