# Generated by Django 5.2.17 on 2026-09-09 23:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_episode_deadline_alter_episode_is_ready_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['number']},
        ),
        migrations.RemoveField(
            model_name='episode',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='is_ready',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='is_translated',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='video_file',
        ),
        migrations.RemoveField(
            model_name='title',
            name='team_members',
        ),
        migrations.RemoveField(
            model_name='title',
            name='telegram_chat_id',
        ),
        migrations.RemoveField(
            model_name='trackassignment',
            name='character_name',
        ),
        migrations.RemoveField(
            model_name='trackassignment',
            name='dubber',
        ),
        migrations.RemoveField(
            model_name='trackassignment',
            name='is_done',
        ),
        migrations.RemoveField(
            model_name='trackassignment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='status',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='telegram_bind_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='telegram_username',
        ),
        migrations.AddField(
            model_name='episode',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='episode',
            name='name',
            field=models.CharField(default='Серия', max_length=255, verbose_name='Название серии'),
        ),
        migrations.AddField(
            model_name='episode',
            name='video_url',
            field=models.URLField(blank=True, default='', verbose_name='Ссылка на видео / Плеер'),
        ),
        migrations.AddField(
            model_name='trackassignment',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Готово'),
        ),
        migrations.AddField(
            model_name='trackassignment',
            name='role',
            field=models.CharField(blank=True, default='Озвучка', max_length=50, verbose_name='Роль на серии'),
        ),
        migrations.AddField(
            model_name='trackassignment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='core.title', verbose_name='Тайтл'),
        ),
        migrations.AlterField(
            model_name='title',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='title',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(default='Участник', max_length=50, verbose_name='Роль в команде'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(default='Аноним', max_length=100, verbose_name='Имя автора')),
                ('text', models.TextField(default='', verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.episode', verbose_name='Серия')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.title', verbose_name='Тайтл')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
